# Generated by Django 3.0.3 on 2020-03-21 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import listing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('medium', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to=listing.models.get_upload_path)),
                ('descrip', models.CharField(max_length=10000)),
                ('stock', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
