# Generated by Django 3.0.3 on 2020-03-24 13:52

from django.db import migrations, models
import listing.models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20200324_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('descrip', models.CharField(max_length=10000)),
                ('image', models.ImageField(upload_to=listing.models.get_upload_path)),
                ('stock', models.IntegerField(validators=[listing.models.validate_gt_zero])),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='stock',
            field=models.IntegerField(validators=[listing.models.validate_gt_zero]),
        ),
    ]
