# Generated by Django 3.0.3 on 2020-03-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20200324_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingedit',
            name='image',
        ),
    ]
