# Generated by Django 3.0.4 on 2020-04-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_auto_20200417_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingedit',
            name='descrip',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
