# Generated by Django 3.0.4 on 2020-04-16 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_auto_20200324_1829'),
        ('shopping_cart', '0003_remove_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.Listing'),
        ),
    ]
